version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/      
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db      

  db:
    image: mariadb
    restart: always
    container_name: db_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3300:3306 
    volumes:
      - dbdata:/var/lib/mysql            

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_phpadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root    
    ports:
      - 88:80 
    depends_on:
      - db        

  redis:
    image: redis
    ports:
       - 6379  

volumes:
  dbdata:
    driver: local       